name: game_hunter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.7.11'

dependencies:
  flutter:
    sdk: flutter

  intro_slider: ^4.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  flutter_bloc: ^8.1.2
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  intl: ^0.18.0
  meta: ^1.8.0
  bloc: ^8.1.1
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_xp.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/